### ISSUE TITLE
403 permission error when executing the github script

### ISSUE THREAD

**Issue by matallen** [redhat-cop/ninja-points#18]
this occurs when running on the pod, but seems ok locally.

from experience, this same error occurs when the script makes too many api calls in quick succession because github has a cap on the number of requests in a time period

`
sh-4.2$ env | grep GITHUB
GITHUB_API_TOKEN=<OBFUSCATED>
sh-4.2$ ^C
sh-4.2$ ./github-stats.py -s 2017-08-13
Traceback (most recent call last):
  File "./github-stats.py", line 155, in <module>
    org_search_issues = get_org_search_issues(session, start_date)
  File "./github-stats.py", line 70, in get_org_search_issues
    return handle_pagination_items(session, query)
  File "./github-stats.py", line 21, in handle_pagination_items
    return pagination_request.json()['items'] + handle_pagination_items(session, pagination_request.links['next']['url'])
......
  File "./github-stats.py", line 21, in handle_pagination_items
    return pagination_request.json()['items'] + handle_pagination_items(session, pagination_request.links['next']['url'])
  File "./github-stats.py", line 18, in handle_pagination_items
    pagination_request.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden
`

**Comment by matallen** [comment]
github has a limit of 5000 calls per hour, except for the search api call which is limited to 30 per minute (for authenticated users, which we are with our token).

I discovered a per_page property to set the page size here ** which helps throttle our requests.

So for the time being that has resolved this issue and allows us to pull 1 year's worth of data.

** https://developer.github.com/v3/#pagination

**Comment by matallen** [comment]
fix / band aid has been applied to hold things together for now. closing...
