### ISSUE TITLE
getgroupprojectdata throws an error when collecting gitlab stats 

### ISSUE THREAD

**Issue by pdelashe** [redhat-cop/ninja-points#63]
Hi!!

Can any of you review this script? as it has been throwing errors since the end of October.. 

2024-11-04T23:01 | Script Execution FAILED | /home/jboss/target/scripts/Gitlab/v1.16/gitlab-stats.py -s 2024-10-23 -o redhat-cop ERROR (stderr): Traceback (most recent call last): File "/home/jboss/target/scripts/Gitlab/v1.16/gitlab-stats.py", line 181, in groupmergerequests = getgroupprojectdata('mergerequests', session, gitlabserver, group, startdate, repomatcher) File "/home/jboss/target/scripts/Gitlab/v1.16/gitlab-stats.py", line 109, in getgroupprojectdata baseurl = "{0}/api/v4/groups/{1}/{2}".format(server, group["id"], datatype) KeyError: 'id' |  

2024-11-04T23:01 | Script Execution FAILED | /home/jboss/target/scripts/Gitlab.ServicesSupport/v1.16/gitlab-stats.py -s 2024-10-23 -o customer-success -m ^(.consulting-delivery-guides\|.consulting-engagement-reports/cer-template)$ ERROR (stderr): Traceback (most recent call last): File "/home/jboss/target/scripts/Gitlab.ServicesSupport/v1.16/gitlab-stats.py", line 181, in groupmergerequests = getgroupprojectdata('mergerequests', session, gitlabserver, group, startdate, repomatcher) File "/home/jboss/target/scripts/Gitlab.ServicesSupport/v1.16/gitlab-stats.py", line 109, in getgroupprojectdata baseurl = "{0}/api/v4/groups/{1}/{2}".format(server, group["id"], datatype) KeyError: 'id'

Thank you!

**Comment by branic** [comment]
The problem is the Access Token for GitLab. I've verified locally that with a good access token the script works. A recent GitLab upgrade forced all tokens to have an expiration date and ones that did not had the expiration date set to Oct. 24th.

I think @sabre1041 or @matallen  will need to fix the token as I don't have access (or know how) to do that.

**Comment by sabre1041** [comment]
> The problem is the Access Token for GitLab. I've verified locally that with a good access token the script works. A recent GitLab upgrade forced all tokens to have an expiration date and ones that did not had the expiration date set to Oct. 24th.
> 
> I think @sabre1041 or @matallen will need to fix the token as I don't have access (or know how) to do that.

I should be able to handle that one

**Comment by pdelashe** [comment]
Thank you sooo much!!!!!!!!!!!!

**Comment by garethahealy** [comment]
based on mails, looks like its been fixed
